#!/usr/bin/env python3
"""Builds the Oryx tiles atlas, the player sprites and the tile font.

    python3 data_rx1/tiles/mkoryx.py [~/Downloads/oryx_megapack/oryx_roguelike_2.0]

With the pack (not in the repo) it rewrites the pack part of data_rx1/tiles/oryx.png (the sheets below, in order,
reflowed to 20 columns of 16x24 cells; the remapper's atlas) and copies the pack's labelled V1 previews into
data_rx1/tiles/ref/ (the remapper's reference_image pictures). Always it then composes the player sprites from
oryx.rec (every %rec: stance pose under every Shield_* and Weapon_* overlay of %rec: equipment, in both idle
frames: a stance's second frame is its cell + 7, one avatar row down), appends them to the atlas, writes them to
oryx_sprites.rec (weapon, shield, icon, anim) and builds web/fonts/Oryx_Tiles.woff (glyph U+E000+i is cell i, so a
tcell cell can hold a tile). Needs Pillow and fontTools. Run it after remapping stances or equipment.
"""
import os, sys
from PIL import Image
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

SHEETS = ["Monsters", "Items", "Terrain", "Terrain_Objects", "Avatar", "Avatar_Equipment"]
PACK_CELLS = 1314  # the sheets' cells; the sprites follow
CW, CH, COLS, PX = 16, 24, 20, 100  # cell, atlas columns, font units per pixel (em = 24 px = 2400)
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(os.path.dirname(here))
atlas_path = os.path.join(here, "oryx.png")

cells = []
if len(sys.argv) > 1:
    src = sys.argv[1]
    for s in SHEETS:
        im = Image.open(os.path.join(src, s + ".png")).convert("RGBA")
        w, h = im.size
        for r in range(h // CH):
            for c in range(w // CW):
                cells.append(im.crop((c * CW, r * CH, c * CW + CW, r * CH + CH)))
        print(s, w // CW, "x", h // CH, "cells, atlas offset", len(cells) - (w // CW) * (h // CH))
    assert len(cells) == PACK_CELLS, len(cells)
    for p in ["preview_creatures", "preview_items", "preview_dungeons"]:
        Image.open(os.path.join(src, "V1", p + ".png")).save(os.path.join(here, "ref", p + ".png"))
else:
    im = Image.open(atlas_path).convert("RGBA")
    for i in range(PACK_CELLS):
        cells.append(im.crop(((i % COLS) * CW, (i // COLS) * CH, (i % COLS) * CW + CW, (i // COLS) * CH + CH)))

def rec(path):
    """{section: {id: icon}} of a recfile."""
    out, section, cur = {}, "", {}
    for line in open(path).read().split("\n") + [""]:
        if line.startswith("%rec: "):
            section = line[6:].strip()
            out.setdefault(section, {})
        elif line.startswith("%") or line.startswith("#"):
            continue
        elif not line.strip():
            if "id" in cur and "icon" in cur:
                out[section][cur["id"]] = int(cur["icon"])
            cur = {}
        elif ":" in line:
            k, v = line.split(":", 1)
            cur[k.strip()] = v.strip()
    return out

mapping = rec(os.path.join(here, "oryx.rec"))
stance, equipment = mapping["stance"], mapping["equipment"]
weapons = [""] + sorted(k[len("Weapon_"):] for k in equipment if k.startswith("Weapon_"))
shields = [""] + sorted(k[len("Shield_"):] for k in equipment if k.startswith("Shield_"))
RANGED = {"bow", "crossbow"}

def compose(frame, layers):
    t = Image.new("RGBA", (CW, CH), (0, 0, 0, 0))
    for i in layers:
        t.alpha_composite(cells[i + frame])
    return t

sprites = ["%rec: sprite\n%doc: Generated by mkoryx.py from the stance and equipment records of oryx.rec: do not edit.\n"]
for w in weapons:
    for s in shields:
        pose = "Stance_" + ("ranged" if w in RANGED else "both" if w and s else "weapon" if w else "shield" if s else "unarmed")
        layers = [stance[pose]] + [equipment[k] for k in ["Shield_" + s, "Weapon_" + w] if k in equipment]
        icon = len(cells)
        cells.append(compose(0, layers))
        cells.append(compose(0, [layers[0] + 7] + layers[1:]))
        sprites.append("".join(f"{k}: {v}\n" for k, v in [("weapon", w), ("shield", s)] if v) + f"icon: {icon}\nanim: {icon + 1}\n")
open(os.path.join(here, "oryx_sprites.rec"), "w").write("\n".join(sprites))

rows = (len(cells) + COLS - 1) // COLS
atlas = Image.new("RGBA", (COLS * CW, rows * CH), (0, 0, 0, 0))
for i, t in enumerate(cells):
    atlas.paste(t, ((i % COLS) * CW, (i // COLS) * CH))
atlas.save(atlas_path)

def glyph(t):
    pen = TTGlyphPen(None)
    a = t.load()
    for y in range(CH):
        x = 0
        while x < CW:
            if a[x, y][3] < 128:
                x += 1
                continue
            x0 = x
            while x < CW and a[x, y][3] >= 128:
                x += 1
            top, bot = (CH - y) * PX, (CH - y - 1) * PX
            pen.moveTo((x0 * PX, bot)); pen.lineTo((x0 * PX, top)); pen.lineTo((x * PX, top)); pen.lineTo((x * PX, bot)); pen.closePath()
    return pen.glyph()

names = [".notdef", "space"] + [f"tile{i}" for i in range(len(cells))]
fb = FontBuilder(CH * PX, isTTF=True)
fb.setupGlyphOrder(names)
fb.setupCharacterMap({0x20: "space", **{0xE000 + i: f"tile{i}" for i in range(len(cells))}})
empty = TTGlyphPen(None).glyph()
fb.setupGlyf({".notdef": empty, "space": empty, **{f"tile{i}": glyph(t) for i, t in enumerate(cells)}})
fb.setupHorizontalMetrics({n: (CW * PX, 0) for n in names})
fb.setupHorizontalHeader(ascent=CH * PX, descent=0)
fb.setupNameTable({"familyName": "Oryx Tiles", "styleName": "Regular"})
fb.setupOS2(version=4, sTypoAscender=CH * PX, sTypoDescender=0, sTypoLineGap=0, usWinAscent=CH * PX, usWinDescent=0, fsSelection=1 << 7)
fb.setupPost()
fb.font.flavor = "woff"
fb.save(os.path.join(root, "web", "fonts", "Oryx_Tiles.woff"))
print(len(cells), "cells,", (len(weapons) * len(shields)), "sprites from", PACK_CELLS)
